#! █▀ █░█ ▄▀█ █▀▄ █▀▀ █▀█ █▀
#! ▄█ █▀█ █▀█ █▄▀ ██▄ █▀▄ ▄█

# *┌────────────────────────────────────────────────────────────────────────────┐
# *│ ВНИМАНИЕ: Этот файл управляется скриптами HyDE! НЕ РЕДАКТИРУЙТЕ ЕГО ВРУЧНУЮ │
# *├────────────────────────────────────────────────────────────────────────────┤
# *│ Чтобы добавить или изменить шейдеры:                                       │
# *│ 1. Положите файлы шейдеров в директорию `./shaders/`                       │
# *│ 2. Запустите команду `shaders.sh --select` для применения и обновления     │
# *│ 3. Чтобы внести кастомные настройки, измените `./shaders/shader-name.inc`  │
# *│                                                                            │
# *│ Скрипт `shaders.sh` автоматически скомпилирует файлы в кэш и применит их. │
# *└────────────────────────────────────────────────────────────────────────────┘

# 🏷️ Имя активного шейдера
# Используется системой для отображения в меню и логах.
$SCREEN_SHADER = "color-vision"

# 📂 Путь к исходному файлу фрагментного шейдера (.frag)
# Это исходный код эффекта, написанный на GLSL.
$SCREEN_SHADER_PATH = "/home/serg/.config/hypr/shaders/color-vision.frag"

# ⚡ Путь к скомпилированному кэшу шейдера
# Сюда скрипты HyDE собирают финальный glsl-код. 
# Вы можете переопределить этот путь в глобальном `../hyde/config.toml`.
$SCREEN_SHADER_COMPILED = ./shaders/.compiled.cache.glsl
