# █▀█ ▄▀█ █▄▄ █▀█ █▀▀ █░█ █ █▀▀ █▀
# █▀▄ █▀█ █▄█ █▄█ █▄▄ █▀█ █ ██▄ ▄█

# ==============================================================================
#      ИСПРАВЛЕННАЯ ПРИВЯЗКА СТОЛОВ: НЕЧЕТНЫЕ СЛЕВА, ЧЕТНЫЕ СПРАВА
# ==============================================================================

# 🖥️ ЛЕВЫЙ МОНИТОР (BenQ EW2775ZH -> HDMI-A-1)
# Дефолтным для левого экрана становится Воркспейс 1
workspace = 1, monitor:HDMI-A-1, default:true, persistent:true
workspace = 3, monitor:HDMI-A-1, persistent:true
workspace = 5, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 9, monitor:HDMI-A-1, persistent:true


# 🎮 ПРАВЫЙ МОНИТОР (Xiaomi Mi Monitor -> DP-1)
# Дефолтным для правого экрана становится Воркспейс 2
workspace = 2, monitor:DP-1, default:true, persistent:true
workspace = 4, monitor:DP-1, persistent:true
workspace = 6, monitor:DP-1, persistent:true
workspace = 8, monitor:DP-1, persistent:true
workspace = 10, monitor:DP-1, persistent:true
