#! ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
#! █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█

# *┌────────────────────────────────────────────────────────────────────────────┐
# *│ ВНИМАНИЕ: Этот файл управляется скриптами HyDE! НЕ РЕДАКТИРУЙТЕ ЕГО ВРУЧНУЮ │
# *├────────────────────────────────────────────────────────────────────────────┤
# *│ Этот файл задает текущий активный стиль анимаций окон и рабочих столов.    │
# *│                                                                            │
# *│ Чтобы добавить или изменить анимации:                                      │
# *│ 1. Создайте или отредактируйте файлы пресетов в директории `./animations/` │
# *│ 2. Выберите нужный пресет через команду `animations.sh --select` (или Rofi) │
# *│                                                                            │
# *│ Официальная документация по кривым и скоростям:                            │
# *│ https://wiki.hypr.land/Configuring/Animations/                             │
# *└────────────────────────────────────────────────────────────────────────────┘

# 🏷️ Имя активного стиля анимаций
# Используется системой для отображения текущего пресета в меню выбора.
$ANIMATION = me-2

# 📂 Путь к файлу конфигурации активного пресета
# Ведет к файлу, где описаны конкретные кривые Безье (Bezier) и скорости для окон.
$ANIMATION_PATH = ./animations/me-2.conf

# 🔌 Подключение настроек выбранного стиля анимации в реальном времени
source = $ANIMATION_PATH
