#! █▀ █░█ ▄▀█ █▀▄ █▀▀ █▀█ █▀
#! ▄█ █▀█ █▀█ █▄▀ ██▄ █▀▄ ▄█

# *┌────────────────────────────────────────────────────────────────────────────┐
# *│ ВНИМАНИЕ: Этот файл управляется скриптами HyDE! НЕ РЕДАКТИРУЙТЕ ЕГО ВРУЧНУЮ │
# *├────────────────────────────────────────────────────────────────────────────┤
# *│ Чтобы добавить или изменить шейдеры:                                       │
# *│ 1. Положите файлы шейдеров в директорию `./shaders/`                       │
# *│ 2. Запустите команду `shaders.sh --select` для применения и обновления     │
# *│ 3. Чтобы внести кастомные настройки, измените `./shaders/shader-name.inc`  │
# *│                                                                            │
# *│ Скрипт `shaders.sh` автоматически скомпилирует файлы в кэш и применит их. │
# *└────────────────────────────────────────────────────────────────────────────┘

# 🏷️ Имя активного шейдера
# Значение "disable" означает, что эффекты отключены и цвета мониторов стандартные.
$SCREEN_SHADER = "disable"

# 📂 Путь к исходному файлу фрагментного шейдера (.frag)
# В данном случае указывает на заглушку отключения эффектов.
$SCREEN_SHADER_PATH = "/home/serg/.config/hypr/shaders/disable.frag"

# ⚡ Путь к скомпилированному кэшу шейдера
# Абсолютный путь к скомпилированному glsl-коду в твоей домашней директории.
$SCREEN_SHADER_COMPILED = /home/serg/.config/hypr/shaders/.compiled.cache.glsl
