#! █░█░█ █▀█ █▀█ █▄▀ █▀▀ █░░ █▀█ █░█░█ █▀
#! ▀▄▀▄▀ █▄█ █▀▄ █░█ █▀░ █▄▄ █▄█ ▀▄▀▄▀ ▄█

# *┌────────────────────────────────────────────────────────────────────────────┐
# *│ ВНИМАНИЕ: Этот файл управляется скриптами HyDE! НЕ РЕДАКТИРУЙТЕ ЕГО ВРУЧНУЮ │
# *├────────────────────────────────────────────────────────────────────────────┤
# *│ Рабочие процессы (Workflows) — это наборы конфигураций для разных задач   │
# *│ (например: Игровой режим, Режим работы, Режим экономии энергии и т.д.).    │
# *│                                                                            │
# *│ Чтобы добавить или изменить профили:                                       │
# *│ 1. Создайте или отредактируйте файлы пресетов в директории `./workflows/`  │
# *│ 2. Запустите команду `workflows.sh --select` для смены текущего режима.    │
# *└────────────────────────────────────────────────────────────────────────────┘

# 🏷️ Имя активного рабочего процесса
$WORKFLOW = default

# 🏷️ Иконка профиля (отображается на панели Waybar или в меню выбора)
$WORKFLOW_ICON = 

# 📝 Описание текущего режима
$WORKFLOW_DESCRIPTION = Unset workflow configuration

# 📂 Путь к файлу конфигурации активного профиля
$WORKFLOWS_PATH = ./workflows/default.conf

# 🔌 Подключение настроек выбранного профиля в реальном времени
source = $WORKFLOWS_PATH
